Angle_mode: preset
DataPath: /storage/VENUS/IPTS-33531/images/mcp
EIC_vals:
  motor_pv: BL10:Mot:rot1
  run_title: HypeCT_test
Max_ang_num: 50
OutPath: /storage/VENUS/IPTS-33531/shared/ai_outputs
QIthresh: 3.5
T: 2.0
Z_NUM:
- 50
- 50
- 50
Z_START:
- 150
- 200
- 250
ai_pre_process_running: true
ai_process_running: true
angle_propose_flag: false
background_cali_paras:
  box_x:
  - 10
  - 10
  - 280
  - 280
  box_y:
  - 10
  - 450
  - 10
  - 450
  height: 200
  if_cali: false
  width: 20
canny_paras:
  a: 0.3
  b: 0.7
  sigma: 4
center_offset: -5.75
crop_cols:
- 0
- 504
debugging: false
eva_paras:
  alpha: 0.6
  beta: 0.4
experiment_title: November22_CrushedRing_B_hyperCT_60Hz_1_8Angsmin_02_50C
hough_paras:
  line_gap: 10
  line_length: 20
ipts: 33531
list_of_runs_reduced: null
load_paras:
  bound: 5
  cent_x: 256
  cent_y: 256
  correct_radius: 1
  if_cali: true
  if_clean: true
  if_save_clean: true
  neighbor_pix_num: 3
  unused_pix_num: 1
  x_off: 2
  y_off: 2
max_iterations: 200
num_ini_ang: 6
num_threads: 256
number_of_obs: 3
number_of_runs_reduced_and_moved: 6
ob_local_path:
- /storage/VENUS/IPTS-33531/images/mcp/OB_November22_CrushedRing_B_hyperCT_60Hz_1_8Angsmin/Run_5127
- /storage/VENUS/IPTS-33531/images/mcp/OB_November22_CrushedRing_B_hyperCT_60Hz_1_8Angsmin/Run_5128
- /storage/VENUS/IPTS-33531/images/mcp/OB_November22_CrushedRing_B_hyperCT_60Hz_1_8Angsmin/Run_5129
- /storage/VENUS/IPTS-33531/images/mcp/OB_November22_CrushedRing_B_hyperCT_60Hz_1_8Angsmin/Run_5130
- /storage/VENUS/IPTS-33531/images/mcp/OB_November22_CrushedRing_B_hyperCT_60Hz_1_8Angsmin/Run_5131
p: 1.2
proton_charge: 2.5
roi_info:
  roi_height: 462
  roi_width: 462
  roi_x: 10
  roi_y: 10
scan_description: hyperCT run
sharpness: 0.0
snr_db: 30.0
step: 3
wav_idx_end:
- 800
wav_idx_start:
- 50
